name: Operator UI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
    paths:
      - 'operator_ui/**'
      - 'core/web/**'
env:
  CACHE_VERSION: 9c3bfa173ea0aca1f9939f8896feb4a4

jobs:
  operator-ui:
    name: Operator UI
    runs-on: ubuntu-latest
    container:
      image: smartcontract/builder:1.0.37
      credentials:
        username: ${{ secrets.DOCKER_READONLY_USERNAME }}
        password: ${{ secrets.DOCKER_READONLY_PASSWORD }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: |
            ~/.npm
            ~/.cache
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn install --frozen-lockfile
      - run: ./tools/bin/restore-solc-cache
      - name: Run Operator UI tests
        run: ./tools/ci/operator_ui_test
